// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "sonarqube:host")
}
func GetInstalledVersion(ctx *pulumi.Context) string {
	return config.Get(ctx, "sonarqube:installedVersion")
}
func GetPass(ctx *pulumi.Context) string {
	return config.Get(ctx, "sonarqube:pass")
}

// Allows ignoring insecure certificates when set to true. Defaults to false. Disabling TLS verification is dangerous and
// should only be done for local testing.
func GetTlsInsecureSkipVerify(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "sonarqube:tlsInsecureSkipVerify")
}
func GetUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "sonarqube:user")
}
