// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    public static class GetQualityProfiles
    {
        public static Task<GetQualityProfilesResult> InvokeAsync(GetQualityProfilesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetQualityProfilesResult>("sonarqube:index/getQualityProfiles:getQualityProfiles", args ?? new GetQualityProfilesArgs(), options.WithDefaults());

        public static Output<GetQualityProfilesResult> Invoke(GetQualityProfilesInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetQualityProfilesResult>("sonarqube:index/getQualityProfiles:getQualityProfiles", args ?? new GetQualityProfilesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetQualityProfilesArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetQualityProfilesArgs()
        {
        }
    }

    public sealed class GetQualityProfilesInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetQualityProfilesInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetQualityProfilesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool IsDefault;
        public readonly string Key;
        public readonly string Language;
        public readonly string Name;

        [OutputConstructor]
        private GetQualityProfilesResult(
            string id,

            bool isDefault,

            string key,

            string language,

            string name)
        {
            Id = id;
            IsDefault = isDefault;
            Key = key;
            Language = language;
            Name = name;
        }
    }
}
