// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    /// <summary>
    /// The provider type for the sonarqube package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [SonarqubeResourceType("pulumi:providers:sonarqube")]
    public partial class Provider : Pulumi.ProviderResource
    {
        [Output("host")]
        public Output<string> Host { get; private set; } = null!;

        [Output("installedVersion")]
        public Output<string?> InstalledVersion { get; private set; } = null!;

        [Output("pass")]
        public Output<string> Pass { get; private set; } = null!;

        [Output("user")]
        public Output<string> User { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs args, CustomResourceOptions? options = null)
            : base("sonarqube", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : Pulumi.ResourceArgs
    {
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        [Input("installedVersion")]
        public Input<string>? InstalledVersion { get; set; }

        [Input("pass", required: true)]
        public Input<string> Pass { get; set; } = null!;

        /// <summary>
        /// Allows ignoring insecure certificates when set to true. Defaults to false. Disabling TLS verification is dangerous and
        /// should only be done for local testing.
        /// </summary>
        [Input("tlsInsecureSkipVerify", json: true)]
        public Input<bool>? TlsInsecureSkipVerify { get; set; }

        [Input("user", required: true)]
        public Input<string> User { get; set; } = null!;

        public ProviderArgs()
        {
        }
    }
}
