// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    [SonarqubeResourceType("sonarqube:index/qualityGateCondition:QualityGateCondition")]
    public partial class QualityGateCondition : Pulumi.CustomResource
    {
        [Output("gateid")]
        public Output<string?> Gateid { get; private set; } = null!;

        [Output("gatename")]
        public Output<string?> Gatename { get; private set; } = null!;

        [Output("metric")]
        public Output<string> Metric { get; private set; } = null!;

        [Output("op")]
        public Output<string> Op { get; private set; } = null!;

        [Output("threshold")]
        public Output<string> Threshold { get; private set; } = null!;


        /// <summary>
        /// Create a QualityGateCondition resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public QualityGateCondition(string name, QualityGateConditionArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityGateCondition:QualityGateCondition", name, args ?? new QualityGateConditionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private QualityGateCondition(string name, Input<string> id, QualityGateConditionState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityGateCondition:QualityGateCondition", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing QualityGateCondition resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static QualityGateCondition Get(string name, Input<string> id, QualityGateConditionState? state = null, CustomResourceOptions? options = null)
        {
            return new QualityGateCondition(name, id, state, options);
        }
    }

    public sealed class QualityGateConditionArgs : Pulumi.ResourceArgs
    {
        [Input("gateid")]
        public Input<string>? Gateid { get; set; }

        [Input("gatename")]
        public Input<string>? Gatename { get; set; }

        [Input("metric", required: true)]
        public Input<string> Metric { get; set; } = null!;

        [Input("op", required: true)]
        public Input<string> Op { get; set; } = null!;

        [Input("threshold", required: true)]
        public Input<string> Threshold { get; set; } = null!;

        public QualityGateConditionArgs()
        {
        }
    }

    public sealed class QualityGateConditionState : Pulumi.ResourceArgs
    {
        [Input("gateid")]
        public Input<string>? Gateid { get; set; }

        [Input("gatename")]
        public Input<string>? Gatename { get; set; }

        [Input("metric")]
        public Input<string>? Metric { get; set; }

        [Input("op")]
        public Input<string>? Op { get; set; }

        [Input("threshold")]
        public Input<string>? Threshold { get; set; }

        public QualityGateConditionState()
        {
        }
    }
}
