// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    [SonarqubeResourceType("sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation")]
    public partial class QualityProfileProjectAssociation : Pulumi.CustomResource
    {
        /// <summary>
        /// Quality profile language
        /// </summary>
        [Output("language")]
        public Output<string> Language { get; private set; } = null!;

        /// <summary>
        /// Project key
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// Quality profile name
        /// </summary>
        [Output("qualityProfile")]
        public Output<string> QualityProfile { get; private set; } = null!;


        /// <summary>
        /// Create a QualityProfileProjectAssociation resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public QualityProfileProjectAssociation(string name, QualityProfileProjectAssociationArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation", name, args ?? new QualityProfileProjectAssociationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private QualityProfileProjectAssociation(string name, Input<string> id, QualityProfileProjectAssociationState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing QualityProfileProjectAssociation resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static QualityProfileProjectAssociation Get(string name, Input<string> id, QualityProfileProjectAssociationState? state = null, CustomResourceOptions? options = null)
        {
            return new QualityProfileProjectAssociation(name, id, state, options);
        }
    }

    public sealed class QualityProfileProjectAssociationArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Quality profile language
        /// </summary>
        [Input("language", required: true)]
        public Input<string> Language { get; set; } = null!;

        /// <summary>
        /// Project key
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// Quality profile name
        /// </summary>
        [Input("qualityProfile", required: true)]
        public Input<string> QualityProfile { get; set; } = null!;

        public QualityProfileProjectAssociationArgs()
        {
        }
    }

    public sealed class QualityProfileProjectAssociationState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Quality profile language
        /// </summary>
        [Input("language")]
        public Input<string>? Language { get; set; }

        /// <summary>
        /// Project key
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Quality profile name
        /// </summary>
        [Input("qualityProfile")]
        public Input<string>? QualityProfile { get; set; }

        public QualityProfileProjectAssociationState()
        {
        }
    }
}
