// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    [SonarqubeResourceType("sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation")]
    public partial class QualityGateProjectAssociation : Pulumi.CustomResource
    {
        [Output("gateid")]
        public Output<string?> Gateid { get; private set; } = null!;

        [Output("gatename")]
        public Output<string?> Gatename { get; private set; } = null!;

        [Output("projectkey")]
        public Output<string> Projectkey { get; private set; } = null!;


        /// <summary>
        /// Create a QualityGateProjectAssociation resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public QualityGateProjectAssociation(string name, QualityGateProjectAssociationArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation", name, args ?? new QualityGateProjectAssociationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private QualityGateProjectAssociation(string name, Input<string> id, QualityGateProjectAssociationState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing QualityGateProjectAssociation resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static QualityGateProjectAssociation Get(string name, Input<string> id, QualityGateProjectAssociationState? state = null, CustomResourceOptions? options = null)
        {
            return new QualityGateProjectAssociation(name, id, state, options);
        }
    }

    public sealed class QualityGateProjectAssociationArgs : Pulumi.ResourceArgs
    {
        [Input("gateid")]
        public Input<string>? Gateid { get; set; }

        [Input("gatename")]
        public Input<string>? Gatename { get; set; }

        [Input("projectkey", required: true)]
        public Input<string> Projectkey { get; set; } = null!;

        public QualityGateProjectAssociationArgs()
        {
        }
    }

    public sealed class QualityGateProjectAssociationState : Pulumi.ResourceArgs
    {
        [Input("gateid")]
        public Input<string>? Gateid { get; set; }

        [Input("gatename")]
        public Input<string>? Gatename { get; set; }

        [Input("projectkey")]
        public Input<string>? Projectkey { get; set; }

        public QualityGateProjectAssociationState()
        {
        }
    }
}
