// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sonarqube
{
    [SonarqubeResourceType("sonarqube:index/userToken:UserToken")]
    public partial class UserToken : Pulumi.CustomResource
    {
        [Output("loginName")]
        public Output<string> LoginName { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("token")]
        public Output<string> Token { get; private set; } = null!;


        /// <summary>
        /// Create a UserToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserToken(string name, UserTokenArgs args, CustomResourceOptions? options = null)
            : base("sonarqube:index/userToken:UserToken", name, args ?? new UserTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserToken(string name, Input<string> id, UserTokenState? state = null, CustomResourceOptions? options = null)
            : base("sonarqube:index/userToken:UserToken", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserToken Get(string name, Input<string> id, UserTokenState? state = null, CustomResourceOptions? options = null)
        {
            return new UserToken(name, id, state, options);
        }
    }

    public sealed class UserTokenArgs : Pulumi.ResourceArgs
    {
        [Input("loginName", required: true)]
        public Input<string> LoginName { get; set; } = null!;

        [Input("name")]
        public Input<string>? Name { get; set; }

        public UserTokenArgs()
        {
        }
    }

    public sealed class UserTokenState : Pulumi.ResourceArgs
    {
        [Input("loginName")]
        public Input<string>? LoginName { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("token")]
        public Input<string>? Token { get; set; }

        public UserTokenState()
        {
        }
    }
}
