# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_projects import *
from .get_quality_profiles import *
from .get_rules import *
from .get_users import *
from .group import *
from .permission import *
from .permission_template import *
from .plugin import *
from .provider import *
from .quality_gate import *
from .quality_gate_condition import *
from .quality_gate_project_association import *
from .quality_profile import *
from .quality_profile_activate_rule import *
from .quality_profile_project_association import *
from .rule import *
from .setting import *
from .sonar_project import *
from .user import *
from .user_token import *
from .web_hook import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_sonarqube.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_sonarqube.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "sonarqube",
  "mod": "index/group",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/group:Group": "Group"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/permission",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/permission:Permission": "Permission"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/permissionTemplate",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/permissionTemplate:PermissionTemplate": "PermissionTemplate"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/plugin",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/plugin:Plugin": "Plugin"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityGate",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityGate:QualityGate": "QualityGate"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityGateCondition",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityGateCondition:QualityGateCondition": "QualityGateCondition"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityGateProjectAssociation",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation": "QualityGateProjectAssociation"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityProfile",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityProfile:QualityProfile": "QualityProfile"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityProfileActivateRule",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityProfileActivateRule:QualityProfileActivateRule": "QualityProfileActivateRule"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/qualityProfileProjectAssociation",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation": "QualityProfileProjectAssociation"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/rule",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/rule:Rule": "Rule"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/setting",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/setting:Setting": "Setting"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/sonarProject",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/sonarProject:SonarProject": "SonarProject"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/user",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/user:User": "User"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/userToken",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/userToken:UserToken": "UserToken"
  }
 },
 {
  "pkg": "sonarqube",
  "mod": "index/webHook",
  "fqn": "pulumi_sonarqube",
  "classes": {
   "sonarqube:index/webHook:WebHook": "WebHook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "sonarqube",
  "token": "pulumi:providers:sonarqube",
  "fqn": "pulumi_sonarqube",
  "class": "Provider"
 }
]
"""
)
