# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['QualityGateProjectAssociationArgs', 'QualityGateProjectAssociation']

@pulumi.input_type
class QualityGateProjectAssociationArgs:
    def __init__(__self__, *,
                 projectkey: pulumi.Input[str],
                 gateid: Optional[pulumi.Input[str]] = None,
                 gatename: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a QualityGateProjectAssociation resource.
        """
        pulumi.set(__self__, "projectkey", projectkey)
        if gateid is not None:
            pulumi.set(__self__, "gateid", gateid)
        if gatename is not None:
            pulumi.set(__self__, "gatename", gatename)

    @property
    @pulumi.getter
    def projectkey(self) -> pulumi.Input[str]:
        return pulumi.get(self, "projectkey")

    @projectkey.setter
    def projectkey(self, value: pulumi.Input[str]):
        pulumi.set(self, "projectkey", value)

    @property
    @pulumi.getter
    def gateid(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gateid")

    @gateid.setter
    def gateid(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gateid", value)

    @property
    @pulumi.getter
    def gatename(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gatename")

    @gatename.setter
    def gatename(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gatename", value)


@pulumi.input_type
class _QualityGateProjectAssociationState:
    def __init__(__self__, *,
                 gateid: Optional[pulumi.Input[str]] = None,
                 gatename: Optional[pulumi.Input[str]] = None,
                 projectkey: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering QualityGateProjectAssociation resources.
        """
        if gateid is not None:
            pulumi.set(__self__, "gateid", gateid)
        if gatename is not None:
            pulumi.set(__self__, "gatename", gatename)
        if projectkey is not None:
            pulumi.set(__self__, "projectkey", projectkey)

    @property
    @pulumi.getter
    def gateid(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gateid")

    @gateid.setter
    def gateid(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gateid", value)

    @property
    @pulumi.getter
    def gatename(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "gatename")

    @gatename.setter
    def gatename(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "gatename", value)

    @property
    @pulumi.getter
    def projectkey(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "projectkey")

    @projectkey.setter
    def projectkey(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "projectkey", value)


class QualityGateProjectAssociation(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 gateid: Optional[pulumi.Input[str]] = None,
                 gatename: Optional[pulumi.Input[str]] = None,
                 projectkey: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a QualityGateProjectAssociation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QualityGateProjectAssociationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QualityGateProjectAssociation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param QualityGateProjectAssociationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QualityGateProjectAssociationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 gateid: Optional[pulumi.Input[str]] = None,
                 gatename: Optional[pulumi.Input[str]] = None,
                 projectkey: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QualityGateProjectAssociationArgs.__new__(QualityGateProjectAssociationArgs)

            __props__.__dict__["gateid"] = gateid
            __props__.__dict__["gatename"] = gatename
            if projectkey is None and not opts.urn:
                raise TypeError("Missing required property 'projectkey'")
            __props__.__dict__["projectkey"] = projectkey
        super(QualityGateProjectAssociation, __self__).__init__(
            'sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            gateid: Optional[pulumi.Input[str]] = None,
            gatename: Optional[pulumi.Input[str]] = None,
            projectkey: Optional[pulumi.Input[str]] = None) -> 'QualityGateProjectAssociation':
        """
        Get an existing QualityGateProjectAssociation resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QualityGateProjectAssociationState.__new__(_QualityGateProjectAssociationState)

        __props__.__dict__["gateid"] = gateid
        __props__.__dict__["gatename"] = gatename
        __props__.__dict__["projectkey"] = projectkey
        return QualityGateProjectAssociation(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def gateid(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "gateid")

    @property
    @pulumi.getter
    def gatename(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "gatename")

    @property
    @pulumi.getter
    def projectkey(self) -> pulumi.Output[str]:
        return pulumi.get(self, "projectkey")

