# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['QualityProfileProjectAssociationArgs', 'QualityProfileProjectAssociation']

@pulumi.input_type
class QualityProfileProjectAssociationArgs:
    def __init__(__self__, *,
                 language: pulumi.Input[str],
                 project: pulumi.Input[str],
                 quality_profile: pulumi.Input[str]):
        """
        The set of arguments for constructing a QualityProfileProjectAssociation resource.
        :param pulumi.Input[str] language: Quality profile language
        :param pulumi.Input[str] project: Project key
        :param pulumi.Input[str] quality_profile: Quality profile name
        """
        pulumi.set(__self__, "language", language)
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "quality_profile", quality_profile)

    @property
    @pulumi.getter
    def language(self) -> pulumi.Input[str]:
        """
        Quality profile language
        """
        return pulumi.get(self, "language")

    @language.setter
    def language(self, value: pulumi.Input[str]):
        pulumi.set(self, "language", value)

    @property
    @pulumi.getter
    def project(self) -> pulumi.Input[str]:
        """
        Project key
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[str]):
        pulumi.set(self, "project", value)

    @property
    @pulumi.getter(name="qualityProfile")
    def quality_profile(self) -> pulumi.Input[str]:
        """
        Quality profile name
        """
        return pulumi.get(self, "quality_profile")

    @quality_profile.setter
    def quality_profile(self, value: pulumi.Input[str]):
        pulumi.set(self, "quality_profile", value)


@pulumi.input_type
class _QualityProfileProjectAssociationState:
    def __init__(__self__, *,
                 language: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 quality_profile: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering QualityProfileProjectAssociation resources.
        :param pulumi.Input[str] language: Quality profile language
        :param pulumi.Input[str] project: Project key
        :param pulumi.Input[str] quality_profile: Quality profile name
        """
        if language is not None:
            pulumi.set(__self__, "language", language)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if quality_profile is not None:
            pulumi.set(__self__, "quality_profile", quality_profile)

    @property
    @pulumi.getter
    def language(self) -> Optional[pulumi.Input[str]]:
        """
        Quality profile language
        """
        return pulumi.get(self, "language")

    @language.setter
    def language(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "language", value)

    @property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[str]]:
        """
        Project key
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "project", value)

    @property
    @pulumi.getter(name="qualityProfile")
    def quality_profile(self) -> Optional[pulumi.Input[str]]:
        """
        Quality profile name
        """
        return pulumi.get(self, "quality_profile")

    @quality_profile.setter
    def quality_profile(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "quality_profile", value)


class QualityProfileProjectAssociation(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 language: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 quality_profile: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a QualityProfileProjectAssociation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] language: Quality profile language
        :param pulumi.Input[str] project: Project key
        :param pulumi.Input[str] quality_profile: Quality profile name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: QualityProfileProjectAssociationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a QualityProfileProjectAssociation resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param QualityProfileProjectAssociationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(QualityProfileProjectAssociationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 language: Optional[pulumi.Input[str]] = None,
                 project: Optional[pulumi.Input[str]] = None,
                 quality_profile: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = QualityProfileProjectAssociationArgs.__new__(QualityProfileProjectAssociationArgs)

            if language is None and not opts.urn:
                raise TypeError("Missing required property 'language'")
            __props__.__dict__["language"] = language
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            if quality_profile is None and not opts.urn:
                raise TypeError("Missing required property 'quality_profile'")
            __props__.__dict__["quality_profile"] = quality_profile
        super(QualityProfileProjectAssociation, __self__).__init__(
            'sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            language: Optional[pulumi.Input[str]] = None,
            project: Optional[pulumi.Input[str]] = None,
            quality_profile: Optional[pulumi.Input[str]] = None) -> 'QualityProfileProjectAssociation':
        """
        Get an existing QualityProfileProjectAssociation resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] language: Quality profile language
        :param pulumi.Input[str] project: Project key
        :param pulumi.Input[str] quality_profile: Quality profile name
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _QualityProfileProjectAssociationState.__new__(_QualityProfileProjectAssociationState)

        __props__.__dict__["language"] = language
        __props__.__dict__["project"] = project
        __props__.__dict__["quality_profile"] = quality_profile
        return QualityProfileProjectAssociation(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def language(self) -> pulumi.Output[str]:
        """
        Quality profile language
        """
        return pulumi.get(self, "language")

    @property
    @pulumi.getter
    def project(self) -> pulumi.Output[str]:
        """
        Project key
        """
        return pulumi.get(self, "project")

    @property
    @pulumi.getter(name="qualityProfile")
    def quality_profile(self) -> pulumi.Output[str]:
        """
        Quality profile name
        """
        return pulumi.get(self, "quality_profile")

