// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package sonarqube

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetRules(ctx *pulumi.Context, args *GetRulesArgs, opts ...pulumi.InvokeOption) (*GetRulesResult, error) {
	var rv GetRulesResult
	err := ctx.Invoke("sonarqube:index/getRules:getRules", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRules.
type GetRulesArgs struct {
	Key string `pulumi:"key"`
}

// A collection of values returned by getRules.
type GetRulesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                  string `pulumi:"id"`
	Key                 string `pulumi:"key"`
	MarkdownDescription string `pulumi:"markdownDescription"`
	Name                string `pulumi:"name"`
	Severity            string `pulumi:"severity"`
	Status              string `pulumi:"status"`
	TemplateKey         string `pulumi:"templateKey"`
	Type                string `pulumi:"type"`
}

func GetRulesOutput(ctx *pulumi.Context, args GetRulesOutputArgs, opts ...pulumi.InvokeOption) GetRulesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetRulesResult, error) {
			args := v.(GetRulesArgs)
			r, err := GetRules(ctx, &args, opts...)
			return *r, err
		}).(GetRulesResultOutput)
}

// A collection of arguments for invoking getRules.
type GetRulesOutputArgs struct {
	Key pulumi.StringInput `pulumi:"key"`
}

func (GetRulesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRulesArgs)(nil)).Elem()
}

// A collection of values returned by getRules.
type GetRulesResultOutput struct{ *pulumi.OutputState }

func (GetRulesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetRulesResult)(nil)).Elem()
}

func (o GetRulesResultOutput) ToGetRulesResultOutput() GetRulesResultOutput {
	return o
}

func (o GetRulesResultOutput) ToGetRulesResultOutputWithContext(ctx context.Context) GetRulesResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetRulesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Key }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) MarkdownDescription() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.MarkdownDescription }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) Severity() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Severity }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) TemplateKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.TemplateKey }).(pulumi.StringOutput)
}

func (o GetRulesResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetRulesResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetRulesResultOutput{})
}
