# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

host: Optional[str]

installedVersion: Optional[str]

pass: Optional[str]

tlsInsecureSkipVerify: Optional[bool]
"""
Allows ignoring insecure certificates when set to true. Defaults to false. Disabling TLS verification is dangerous and
should only be done for local testing.
"""

user: Optional[str]

