// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getQualityProfiles(args: GetQualityProfilesArgs, opts?: pulumi.InvokeOptions): Promise<GetQualityProfilesResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("sonarqube:index/getQualityProfiles:getQualityProfiles", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getQualityProfiles.
 */
export interface GetQualityProfilesArgs {
    name: string;
}

/**
 * A collection of values returned by getQualityProfiles.
 */
export interface GetQualityProfilesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly isDefault: boolean;
    readonly key: string;
    readonly language: string;
    readonly name: string;
}

export function getQualityProfilesOutput(args: GetQualityProfilesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetQualityProfilesResult> {
    return pulumi.output(args).apply(a => getQualityProfiles(a, opts))
}

/**
 * A collection of arguments for invoking getQualityProfiles.
 */
export interface GetQualityProfilesOutputArgs {
    name: pulumi.Input<string>;
}
