// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Permission extends pulumi.CustomResource {
    /**
     * Get an existing Permission resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PermissionState, opts?: pulumi.CustomResourceOptions): Permission {
        return new Permission(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/permission:Permission';

    /**
     * Returns true if the given object is an instance of Permission.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Permission {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Permission.__pulumiType;
    }

    public readonly groupName!: pulumi.Output<string | undefined>;
    public readonly loginName!: pulumi.Output<string | undefined>;
    public readonly permissions!: pulumi.Output<string[]>;
    public readonly projectKey!: pulumi.Output<string | undefined>;
    public readonly templateId!: pulumi.Output<string | undefined>;
    public readonly templateName!: pulumi.Output<string | undefined>;

    /**
     * Create a Permission resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PermissionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PermissionArgs | PermissionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PermissionState | undefined;
            resourceInputs["groupName"] = state ? state.groupName : undefined;
            resourceInputs["loginName"] = state ? state.loginName : undefined;
            resourceInputs["permissions"] = state ? state.permissions : undefined;
            resourceInputs["projectKey"] = state ? state.projectKey : undefined;
            resourceInputs["templateId"] = state ? state.templateId : undefined;
            resourceInputs["templateName"] = state ? state.templateName : undefined;
        } else {
            const args = argsOrState as PermissionArgs | undefined;
            if ((!args || args.permissions === undefined) && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            resourceInputs["groupName"] = args ? args.groupName : undefined;
            resourceInputs["loginName"] = args ? args.loginName : undefined;
            resourceInputs["permissions"] = args ? args.permissions : undefined;
            resourceInputs["projectKey"] = args ? args.projectKey : undefined;
            resourceInputs["templateId"] = args ? args.templateId : undefined;
            resourceInputs["templateName"] = args ? args.templateName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Permission.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Permission resources.
 */
export interface PermissionState {
    groupName?: pulumi.Input<string>;
    loginName?: pulumi.Input<string>;
    permissions?: pulumi.Input<pulumi.Input<string>[]>;
    projectKey?: pulumi.Input<string>;
    templateId?: pulumi.Input<string>;
    templateName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Permission resource.
 */
export interface PermissionArgs {
    groupName?: pulumi.Input<string>;
    loginName?: pulumi.Input<string>;
    permissions: pulumi.Input<pulumi.Input<string>[]>;
    projectKey?: pulumi.Input<string>;
    templateId?: pulumi.Input<string>;
    templateName?: pulumi.Input<string>;
}
