// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class QualityProfileProjectAssociation extends pulumi.CustomResource {
    /**
     * Get an existing QualityProfileProjectAssociation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: QualityProfileProjectAssociationState, opts?: pulumi.CustomResourceOptions): QualityProfileProjectAssociation {
        return new QualityProfileProjectAssociation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/qualityProfileProjectAssociation:QualityProfileProjectAssociation';

    /**
     * Returns true if the given object is an instance of QualityProfileProjectAssociation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is QualityProfileProjectAssociation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === QualityProfileProjectAssociation.__pulumiType;
    }

    /**
     * Quality profile language
     */
    public readonly language!: pulumi.Output<string>;
    /**
     * Project key
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * Quality profile name
     */
    public readonly qualityProfile!: pulumi.Output<string>;

    /**
     * Create a QualityProfileProjectAssociation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: QualityProfileProjectAssociationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: QualityProfileProjectAssociationArgs | QualityProfileProjectAssociationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as QualityProfileProjectAssociationState | undefined;
            resourceInputs["language"] = state ? state.language : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["qualityProfile"] = state ? state.qualityProfile : undefined;
        } else {
            const args = argsOrState as QualityProfileProjectAssociationArgs | undefined;
            if ((!args || args.language === undefined) && !opts.urn) {
                throw new Error("Missing required property 'language'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.qualityProfile === undefined) && !opts.urn) {
                throw new Error("Missing required property 'qualityProfile'");
            }
            resourceInputs["language"] = args ? args.language : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["qualityProfile"] = args ? args.qualityProfile : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(QualityProfileProjectAssociation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering QualityProfileProjectAssociation resources.
 */
export interface QualityProfileProjectAssociationState {
    /**
     * Quality profile language
     */
    language?: pulumi.Input<string>;
    /**
     * Project key
     */
    project?: pulumi.Input<string>;
    /**
     * Quality profile name
     */
    qualityProfile?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a QualityProfileProjectAssociation resource.
 */
export interface QualityProfileProjectAssociationArgs {
    /**
     * Quality profile language
     */
    language: pulumi.Input<string>;
    /**
     * Project key
     */
    project: pulumi.Input<string>;
    /**
     * Quality profile name
     */
    qualityProfile: pulumi.Input<string>;
}
