// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class QualityGateProjectAssociation extends pulumi.CustomResource {
    /**
     * Get an existing QualityGateProjectAssociation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: QualityGateProjectAssociationState, opts?: pulumi.CustomResourceOptions): QualityGateProjectAssociation {
        return new QualityGateProjectAssociation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/qualityGateProjectAssociation:QualityGateProjectAssociation';

    /**
     * Returns true if the given object is an instance of QualityGateProjectAssociation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is QualityGateProjectAssociation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === QualityGateProjectAssociation.__pulumiType;
    }

    public readonly gateid!: pulumi.Output<string | undefined>;
    public readonly gatename!: pulumi.Output<string | undefined>;
    public readonly projectkey!: pulumi.Output<string>;

    /**
     * Create a QualityGateProjectAssociation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: QualityGateProjectAssociationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: QualityGateProjectAssociationArgs | QualityGateProjectAssociationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as QualityGateProjectAssociationState | undefined;
            resourceInputs["gateid"] = state ? state.gateid : undefined;
            resourceInputs["gatename"] = state ? state.gatename : undefined;
            resourceInputs["projectkey"] = state ? state.projectkey : undefined;
        } else {
            const args = argsOrState as QualityGateProjectAssociationArgs | undefined;
            if ((!args || args.projectkey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectkey'");
            }
            resourceInputs["gateid"] = args ? args.gateid : undefined;
            resourceInputs["gatename"] = args ? args.gatename : undefined;
            resourceInputs["projectkey"] = args ? args.projectkey : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(QualityGateProjectAssociation.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering QualityGateProjectAssociation resources.
 */
export interface QualityGateProjectAssociationState {
    gateid?: pulumi.Input<string>;
    gatename?: pulumi.Input<string>;
    projectkey?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a QualityGateProjectAssociation resource.
 */
export interface QualityGateProjectAssociationArgs {
    gateid?: pulumi.Input<string>;
    gatename?: pulumi.Input<string>;
    projectkey: pulumi.Input<string>;
}
