// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class QualityGateCondition extends pulumi.CustomResource {
    /**
     * Get an existing QualityGateCondition resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: QualityGateConditionState, opts?: pulumi.CustomResourceOptions): QualityGateCondition {
        return new QualityGateCondition(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sonarqube:index/qualityGateCondition:QualityGateCondition';

    /**
     * Returns true if the given object is an instance of QualityGateCondition.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is QualityGateCondition {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === QualityGateCondition.__pulumiType;
    }

    public readonly gateid!: pulumi.Output<string | undefined>;
    public readonly gatename!: pulumi.Output<string | undefined>;
    public readonly metric!: pulumi.Output<string>;
    public readonly op!: pulumi.Output<string>;
    public readonly threshold!: pulumi.Output<string>;

    /**
     * Create a QualityGateCondition resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: QualityGateConditionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: QualityGateConditionArgs | QualityGateConditionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as QualityGateConditionState | undefined;
            resourceInputs["gateid"] = state ? state.gateid : undefined;
            resourceInputs["gatename"] = state ? state.gatename : undefined;
            resourceInputs["metric"] = state ? state.metric : undefined;
            resourceInputs["op"] = state ? state.op : undefined;
            resourceInputs["threshold"] = state ? state.threshold : undefined;
        } else {
            const args = argsOrState as QualityGateConditionArgs | undefined;
            if ((!args || args.metric === undefined) && !opts.urn) {
                throw new Error("Missing required property 'metric'");
            }
            if ((!args || args.op === undefined) && !opts.urn) {
                throw new Error("Missing required property 'op'");
            }
            if ((!args || args.threshold === undefined) && !opts.urn) {
                throw new Error("Missing required property 'threshold'");
            }
            resourceInputs["gateid"] = args ? args.gateid : undefined;
            resourceInputs["gatename"] = args ? args.gatename : undefined;
            resourceInputs["metric"] = args ? args.metric : undefined;
            resourceInputs["op"] = args ? args.op : undefined;
            resourceInputs["threshold"] = args ? args.threshold : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(QualityGateCondition.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering QualityGateCondition resources.
 */
export interface QualityGateConditionState {
    gateid?: pulumi.Input<string>;
    gatename?: pulumi.Input<string>;
    metric?: pulumi.Input<string>;
    op?: pulumi.Input<string>;
    threshold?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a QualityGateCondition resource.
 */
export interface QualityGateConditionArgs {
    gateid?: pulumi.Input<string>;
    gatename?: pulumi.Input<string>;
    metric: pulumi.Input<string>;
    op: pulumi.Input<string>;
    threshold: pulumi.Input<string>;
}
